export const BUS_ACTION_TYPES = {
  FETCH_BUS_ROUTES_START: "bus/FETCH_BUS_ROUTES_START",
  FETCH_BUS_ROUTES_SUCCESS: "bus/FETCH_BUS_ROUTES_SUCCESS",
  FETCH_BUS_ROUTES_FAILED: "bus/FETCH_BUS_ROUTES_FAILED",
};
