export const SCENIC_SPOT_ACTION_TYPES = {
  FETCH_SCENIC_SPOT_START: "scenicSpot/FETCH_SCENIC_SPOT_START",
  FETCH_SCENIC_SPOT_SUCCESS: "scenicSpot/FETCH_SCENIC_SPOT_SUCCSEE",
  FETCH_SCENIC_SPOT_FAILED: "scenicSpot/FETCH_SCENIC_SPOT_FAILED",
};
